### ISSUE TITLE
Epoll event loop seems to be causing issues

### ISSUE THREAD

**Issue by dsyer** [reactor/reactor-ipc#16]
```
2016-05-28 14:28:52.238  WARN 14266 --- [tcp-client-io-1] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

io.netty.channel.unix.Errors$NativeIoException: epoll_ctl() failed: No such file or directory
    at io.netty.channel.unix.Errors.newIOException(Errors.java:115) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
    at io.netty.channel.epoll.Native.epollCtlMod(Native.java:128) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
    at io.netty.channel.epoll.EpollEventLoop.modify(EpollEventLoop.java:145) [netty-all-4.1.0.Final.jar:4.1.0.Final]
    at io.netty.channel.epoll.AbstractEpollChannel.modifyEvents(AbstractEpollChannel.java:183) [netty-all-4.1.0.Final.jar:4.1.0.Final]
    at io.netty.channel.epoll.AbstractEpollChannel.clearFlag(AbstractEpollChannel.java:81) [netty-all-4.1.0.Final.jar:4.1.0.Final]
    at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.clearEpollIn0(AbstractEpollChannel.java:464) [netty-all-4.1.0.Final.jar:4.1.0.Final]
    at io.netty.channel.epoll.AbstractEpollChannel.clearEpollIn(AbstractEpollChannel.java:161) [netty-all-4.1.0.Final.jar:4.1.0.Final]
    at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollInFinally(AbstractEpollChannel.java:337) [netty-all-4.1.0.Final.jar:4.1.0.Final]
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:985) [netty-all-4.1.0.Final.jar:4.1.0.Final]
    at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:360) [netty-all-4.1.0.Final.jar:4.1.0.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339) [netty-all-4.1.0.Final.jar:4.1.0.Final]
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:287) [netty-all-4.1.0.Final.jar:4.1.0.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) [netty-all-4.1.0.Final.jar:4.1.0.Final]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]

```

It's also impossible to switch it off. Here's the code in `NettyNativeDetector`:

```
    static {
        if (!PlatformDependent.isWindows()
                &&
                Boolean.parseBoolean(System.getProperty("reactor.io.epoll", "true"))) {
                epoll = EpollDetector.hasEpoll();
        }
        else {
            epoll = true;
        }
    }
```

the else clause is always hit, even if you try and set the system property explicitly.

**Comment by rstoyanchev** [comment]
@dsyer FYI on a related fix https://github.com/reactor/reactor-io/commit/a7ea250791c28b48665fe7f5e92b380654378584. It may not make a difference but worth checking.
